#!/bin/sh

case "$1" in
    lock)
        i3lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        i3lock && sudo s2ram
        ;;
    hibernate)
        i3lock && sudo s2ram
        ;;
    reboot)
        sudo reboot
        ;;
    shutdown)
        sudo shutdown
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
